### ISSUE TITLE
Can't call 'extend' as constructor 😳

### ISSUE THREAD

**Issue by rowdyrabouw** [EddyVerbruggen/nativescript-barcodescanner#123]
Without changing our own code this error occures suddenly on Android after I have given permission to use the camera and it's about to open te scanner. Tried it with version 2.7.1 and 2.7.2.
Testing on Samsung Galaxy J5 with Android 7.0 connected to MacBook (tns run android).

Any idea what's going wrong?
Can share the project if you want.

```JS: ERROR Error: Uncaught (in promise): Error: Can't call 'extend' as constructor
JS: Error: Can't call 'extend' as constructor
JS:     at onPermissionGranted (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/tns_modules/nativescript-barcodescanner/barcodescanner.js:147:47)
JS:     at file:///data/data/nl.nn.mijninkomenvoorlater/files/app/tns_modules/nativescript-barcodescanner/barcodescanner.js:205:13
JS:     at new ZoneAwarePromise (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:776:29)
JS:     at BarcodeScanner.scan (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/tns_modules/nativescript-barcodescanner/barcodescanner.js:97:16)
JS:     at PensscanComponent.scanQR (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/components/pensscan/pensscan.component.js:62:29)
JS:     at PensscanComponent.ngOnInit (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/components/pensscan/pensscan.component.js:44:14)
JS:     at checkAndUpdateDirectiveInline (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/tns_modules/@angular/core/bundles/core.umd.js:10822:19)
JS:     at checkAndUpdateNodeInline (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/tns_modules/@angular/core/bundles/core.umd.js:12245:17)
JS:     at checkAndUpdateNode (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/tns_modules/@angular/core/bundles/core.umd.js:12184:16)
JS:     at prodCheckAndUpdateNode (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/tns_modules/@angular/core/bundles/core.umd.js:12711:5)
JS:     at Object.eval [as updateDirectives] (ng:///AppModule/PensscanComponent_Host.ngfactory.js:19:5)
JS:     at Object.updateDirectives (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/tns_modules/@angular/core/bundles/core.umd.js:12625:72)
JS:     at Object.checkAndUpdateView (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/tns_modules/@angular/core/bundles/core.umd.js:12151:14)
JS:     at ViewRef_.detectChanges (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/tns_modules/@angular/core/bundles/core.umd.js:10225:63)
JS:     at RouterOutlet.activateWith (file:///data/data/nl.nn.mijninkomenvoorlater/files/app/tns_modules/@angular/router/bundles/router.umd.js:5345:42)```

**Comment by EddyVerbruggen** [comment]
That change was part of #121 which was released with 2.7.2 so 2.7.1 should definitely not show this error. Can you please doublecheck you're not using something like `~2.7.1`? If 2.7.1 works I can release a fix with 2.7.3.

**Comment by rowdyrabouw** [comment]
Ok, will check immediately

**Comment by rowdyrabouw** [comment]
Yes, 2.7.1 does work. I really thought I tested it first with 2.7.1, but probably did a npm install somewhere this week. I now have ```2.7.1``` in my package.json.

**Comment by EddyVerbruggen** [comment]
2.7.3 has been released, thanks for the report! 👍
