### ISSUE TITLE
Adding plugin causes java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by badrihippo** [EddyVerbruggen/nativescript-barcodescanner#166]
I'm running into a problem when trying to add this plugin to my project. When I try to compile, the build fails with this error:

    Failed to build plugin nativescript-barcodescanner : 
    Error: Command ./gradlew failed with exit code 1 Error output: 
     Exception in thread "main" java.util.zip.ZipException: error in opening zip file

The problem came up when I upgraded my NativeScript from `3.2.0` to `4.2.4`. However, it occurs only when `nativescript-barcodescanner` is installed. When I remove the plugin, the rest of the project compiles successfully, which means it's not a general environment error like https://github.com/NativeScript/NativeScript/issues/3930.

I tried clearing `node_modules` and reinstalling all dependencies, as well as installing earlier versions of this plugin; however that didn't help either.

# Steps to reproduce

Here is the minimum test case I could come up with. First, the environment details:

    $ tns info
    ✔ Getting NativeScript components versions information...
    ✔ Component nativescript has 4.2.4 version and is up to date.
    ✔ Component tns-core-modules has 4.2.1 version and is up to date.
    ✔ Component tns-android has 4.2.0 version and is up to date.
    ✔ Component tns-ios has 4.2.0 version and is up to date.

I basically create a new project, and the `nativescript-barcodescanner` plugin, and try to compile:

    $ tns create bartest
    npm notice created a lockfile as package-lock.json. You should commit this file.
    added 3 packages in 295.509s
    Project bartest was successfully created.
    
    $ cd bartest
    $ tns plugin add nativescript-barcodescanner
    + nativescript-barcodescanner@2.7.8
    added 1 package in 97.781s
    Successfully installed plugin nativescript-barcodescanner.
    
    $ tns prepare android
    Copying template files...
    Platform android successfully added. v4.2.0
    Preparing project...
    Successfully prepared plugin nativescript-barcodescanner for android.
    Successfully prepared plugin nativescript-theme-core for android.
    Successfully prepared plugin tns-core-modules for android.
    Successfully prepared plugin tns-core-modules-widgets for android.
    Failed to build plugin nativescript-barcodescanner : 
    Error: Command ./gradlew failed with exit code 1 Error output: 
     Exception in thread "main" java.util.zip.ZipException: error in opening zip file
    	at java.util.zip.ZipFile.open(Native Method)
    	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
    	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
    	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
    	at org.gradle.wrapper.Install.unzip(Install.java:215)
    	at org.gradle.wrapper.Install.access$600(Install.java:27)
    	at org.gradle.wrapper.Install$1.call(Install.java:75)
    	at org.gradle.wrapper.Install$1.call(Install.java:48)
    	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
    	at org.gradle.wrapper.Install.createDist(Install.java:48)
    	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
       	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

Also attached is the output of the full debug output (`tns prepare android --log trace`): [tns-debug.txt](https://github.com/EddyVerbruggen/nativescript-barcodescanner/files/2483039/tns-debug.txt)

Any idea what the problem could be, or how I could trace it down? Have I come to the right place?

**Comment by badrihippo** [comment]
It turned out  the problem wasn't related to this plugin. Gradle turned out to be the culprit after all.

NativeScript seems to use different gradle versions for different tasks: in my case, `gradle-4.4-all.zip` for app builds but `gradle-4.4-bin.zip` for plugins. The `-bin.zip` one was faulty which is why ordinary builds worked but failed when the project required a second, plugin-specific build. Replacing that faulty zip solved the problem.

I've written more details in [this StackOverflow answer](https://stackoverflow.com/a/52984237/1196444).
