### ISSUE TITLE
[iOS] Crash with NativeScript 8 and JSC runtime

### ISSUE THREAD

**Issue by jessorlisa** [EddyVerbruggen/nativescript-barcodescanner#268]
**Environment**
 - CLI: `├── nativescript@8.0.2`
 - Cross-platform modules: `@nativescript/core@8.0.8`
 - Android Runtime: -
 - iOS Runtime: `├── @nativescript/ios@6.5.4` (**JSC**)
 - Plugin(s):
   `├── nativescript-barcodescanner@4.1.1`
   `├── @nativescript/webpack@beta`

**Describe the bug**
Using the plugin with the iOS JSC runtime causes a crash starting with v4 of this plugin:

```
NativeScript caught signal 11.
Native Stack:
1   0x10545b018 sig_handler(int)
2   0x1e9334d9c <redacted>
3   0x1053d9664 NativeScript::NSObjectAlloc(JSC::ExecState*)
4   0x105f837cc llint_entry
5   0x105f80f28 llint_entry
6   0x105f81ed4 llint_entry
7   0x105f81ed4 llint_entry
8   0x105f80f28 llint_entry
9   0x105f80e80 llint_entry
10  0x105f80f28 llint_entry
11  0x105f80f28 llint_entry
12  0x105f625e8 vmEntryToJavaScript
13  0x105510e48 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)
14  0x10544b8e8 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::callFunction(JSC::JSValue const&, JSC::ArgList const&, void*)
15  0x10544b2f4 NativeScript::ObjCMethodCallback::ffiClosureCallback(void*, void**, void*)
16  0x10544c428 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
17  0x105fb7388 ffi_closure_SYSV_inner
18  0x105fb81b4 .Ldo_closure
19  0x1a3002a64 <redacted>
20  0x1a30031e8 <redacted>
21  0x1a2f45474 <redacted>
22  0x1a2f4610c <redacted>
23  0x1a2f47490 <redacted>
24  0x1a2f2a4c4 <redacted>
25  0x1a3bc26d4 <redacted>
26  0x1a4038424 <redacted>
27  0x1a403ebac <redacted>
28  0x1a404a16c <redacted>
29  0x1a3f92578 <redacted>
30  0x1a3fbd2c8 <redacted>
31  0x1a36e06c8 <redacted>
JS Stack:
alloc([native code])
at BarcodeScanner(file: app/Users/jessorlisa/Development/jessorlisa/barcodedemo/src/barcodescanner.ts:113:48)
at HelloWorldModel(file: app/main-view-model.ts:10:44)
at navigatingTo(file: app/main-page.ts:7:43)
at _handleEvent(file: node_modules/@nativescript/core/data/observable/index.js:233:0)
at notify(file: node_modules/@nativescript/core/data/observable/index.js:216:0)
at onNavigatingTo(file: node_modules/@nativescript/core/ui/page/page-common.js:90:0)
at file: node_modules/@nativescript/core/ui/page/index.ios.js:79:0
at UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/index.ios.js:336:0)
at file:///app/bundle.js:684:67
at ./app.ts(file:///app/bundle.js:696:34)
at __webpack_require__(file: app/webpack/bootstrap:816:0)
at checkDeferredModules(file: app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at
at asyncFunctionResume
at
at promiseReactionJob
```

**To Reproduce**
```
git clone https://github.com/EddyVerbruggen/nativescript-barcodescanner barcodedemo
cd barcodedemo/demo
npm install @nativescript/ios@JSC
ns clean
cd ../src
npm run demo.ios
```

**Expected behavior**
No crash.

**Additional context**
The bug was already reported once and closed as solved, which is sadly not the case:

- https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues/251

Switching the iOS runtime to v8 everything works as expected, but sadly this is no option, as there are a lot of issues with the v8 runtime. **The JSC runtime version is considered to be compatible with {N}7/8.**

Downgrading to any version before 4 is no option either as those versions are not compatible with webpack5.
 
---
Please let me know if there is anything else you need. Thanks!

**Comment by jessorlisa** [comment]
The crash seems to be related to the volume observer:
https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/6e08f387e9312e896930effbf597acca22b1a845/src/barcodescanner.ios.ts#L112-L115

Once removed no crash is happening. Maybe this helps in isolating the issue.

```
    //if (this._device && this._device.hasTorch && this._device.hasFlash) {
    //  this._observer = VolumeObserverClass.alloc();
    //  this._observer["_owner"] = this;
    //}
```
