### ISSUE TITLE
Error: Command xcodebuild failed with exit code 65 on Apple Silicon (M1)

### ISSUE THREAD

**Issue by andrewm-mitchells** [EddyVerbruggen/nativescript-barcodescanner#280]
Hello,

I'm experiencing an issue building/running my app with barcodescanner package. This is easy to replicate - create new drawer template project, add `nativescript-barcodescanner` and try to build.

Here's an error with stack trace:

```
ld: warning: directory not found for option '-F/Users/andrew/Mobile/App/platforms/ios/build/Debug-iphonesimulator/DBCameraButton'
ld: warning: directory not found for option '-F/Users/andrew/Mobile/App/platforms/ios/build/Debug-iphonesimulator/DKCamera'
ld: warning: directory not found for option '-F/Users/andrew/Mobile/App/platforms/ios/build/Debug-iphonesimulator/DKImagePickerController'
ld: warning: directory not found for option '-F/Users/andrew/Mobile/App/platforms/ios/build/Debug-iphonesimulator/DKPhotoGallery'
ld: warning: directory not found for option '-F/Users/andrew/Mobile/App/platforms/ios/build/Debug-iphonesimulator/IQKeyboardManager'
ld: warning: directory not found for option '-F/Users/andrew/Mobile/App/platforms/ios/build/Debug-iphonesimulator/IQMediaPickerController'
ld: warning: directory not found for option '-F/Users/andrew/Mobile/App/platforms/ios/build/Debug-iphonesimulator/QBImagePickerController'
ld: warning: directory not found for option '-F/Users/andrew/Mobile/App/platforms/ios/build/Debug-iphonesimulator/SCSiriWaveformView'
ld: warning: directory not found for option '-F/Users/andrew/Mobile/App/platforms/ios/build/Debug-iphonesimulator/SDWebImage'
ld: warning: directory not found for option '-F/Users/andrew/Mobile/App/platforms/ios/build/Debug-iphonesimulator/SwiftyGif'
ld: framework not found DBCameraButton
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/andrew/Library/Developer/Xcode/DerivedData/App-fioaochftlqehoajtbiulqrwsmrn/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/App.build/Objects-normal/i386/Binary/App normal i386 (in target 'App' from project 'App')
(1 failure)
Command xcodebuild failed with exit code 65
Error: Command xcodebuild failed with exit code 65
    at Errors.failWithOptions (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:157:27)
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:130:21)
    at XcodebuildCommandService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:34:30)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Node version: `v16.14.0`

`ns-info`: 
```
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.2.2 version and is up to date.
✔ Component @nativescript/core has 8.2.1 version and is up to date.
✔ Component @nativescript/ios has 8.2.1 version and is up to date.
✔ Component @nativescript/android has 8.2.2 version and is up to date.
```

`package.json`

```
"dependencies": {
    "@angular/animations": "^13.2.5",
    "@angular/common": "^13.2.5",
    "@angular/compiler": "^13.2.5",
    "@angular/core": "^13.2.5",
    "@angular/forms": "^13.2.5",
    "@angular/platform-browser": "^13.2.5",
    "@angular/platform-browser-dynamic": "^13.2.5",
    "@angular/router": "^13.2.5",
    "@nativescript-community/universal-links": "^2.0.3",
    "@nativescript/angular": "^13.0.0",
    "@nativescript/appversion": "~2.0.0",
    "@nativescript/background-http": "^5.0.2",
    "@nativescript/core": "~8.2.0",
    "@nativescript/datetimepicker": "^2.1.9",
    "@nativescript/email": "^2.0.0",
    "@nativescript/imagepicker": "^1.0.5",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/social-share": "^2.0.1",
    "@nativescript/theme": "~3.0.2",
    "crypto-js": "^4.1.1",
    "eslint": "^7.25.0",
    "nativescript-barcodescanner": "~4.1.2",
    "nativescript-mediafilepicker": "^4.0.2",
    "nativescript-phone": "^3.0.1",
    "nativescript-plugin-universal-links": "^1.0.2",
    "nativescript-ui-gauge": "^8.0.0",
    "nativescript-ui-listview": "~10.0.2",
    "nativescript-ui-sidedrawer": "~10.0.2",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~7.5.0",
    "shelljs": "^0.8.4",
    "zone.js": "~0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^13.2.5",
    "@angular/compiler-cli": "^13.2.5",
    "@nativescript/android": "8.2.2",
    "@nativescript/ios": "8.2.1",
    "@nativescript/types": "~8.1.1",
    "@nativescript/webpack": "~5.0.5",
    "@ngtools/webpack": "^13.2.0",
    "codelyzer": "~6.0.0",
    "sass": "^1.49.9",
    "semver": "^7.3.4",
    "typescript": "~4.5.5"
  }
```

**Comment by sambbeadle** [comment]
Has there been any update on this @EddyVerbruggen?
This is making it next to impossible to build some apps using this plugin on m1 Macs...

**Comment by kayintveen** [comment]
Same here.

**Comment by darklight365** [comment]
See this updated plugin in the nstudio common plugins https://www.npmjs.com/package/@nstudio/nativescript-barcodescanner

It should be a drop in replacement for the current plugin, just need to update your references to point to '@nstudio/nativescript-barcodescanner' instead of 'nativescript-barcodescanner'

@kayintveen @sambbeadle @andrewm-mitchells
