### ISSUE TITLE
Conflict with another similar plugin

### ISSUE THREAD

**Issue by xerotolerant** [EddyVerbruggen/nativescript-barcodescanner#42]
Hello this plugins is conflicting with nativesript-zxing and I need both for my application.

Exception in thread "main" java.lang.IllegalArgumentException: Class com.google.zxing.pdf417.PDF417ResultMetadata conflict: /Users/kheenan/Documents/ExerClub/platforms/android/build/intermediates/exploded-aar/barcodescanner-release-2.0.2/jars/classes.jar and /Users/kheenan/.gradle/caches/modules-2/files-2.1/com.google.zxing/core/3.2.1/2287494d4f5f9f3a9a2bb6980e3f32053721b315/core-3.2.1.jar
	at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:39)
	at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

I need both one to scan qr code and another to display them. 
This one scans qrcodes really well but as far as I can tell cannot display them.
The other displays them but will only scan stored images. any thoughts on how I can get them to play nice together?

**Comment by NathanaelA** [comment]
The answer has been posted in https://github.com/NathanaelA/nativescript-zxing/issues/4 -- you can close this issue.

**Comment by xerotolerant** [comment]
Ok thanks. That worked
